// src/main/resources/assets/admin/settings-extra-html.jsx
var ExtraHtmlSettingsPage = React.createClass({
    render: function() {
        return (
            <div id="site-settings-page">
                <h2 className="page-header">Extra HTML and CSS</h2>
                <form>
                    <div className="form-group">
                        <label>Head section HTML</label>
                        <ReactTextarea className="form-control" name="headHtml" />
                    </div>
                    <div className="form-group">
                        <label>Footer section HTML</label>
                        <textarea className="form-control" name="footerHtml"></textarea>
                    </div>
                    <div className="form-group">
                        <label>Extra CSS</label>
                        <textarea className="form-control" name="footerHtml"></textarea>
                    </div>
                    <button type="submit" className="btn btn-primary">Save</button>
                </form>            
            </div>
        );
    }
});

// src/main/resources/assets/app-screens/settings-extra-html.vue
<style>
 
</style>



<template>
    <div>
        <loading-div v-if='$loadingRouteData'></loading-div>
        <div v-if="!$loadingRouteData">
            <h3>Extra HTML and CSS</h3>
            <form @submit.prevent='save'>
                <div class="form-group">
                    <label>Head HTML</label>
                    <textarea class="form-control" name="headHtml" v-model="data.headHtml"></textarea>
                </div>
                <div class="form-group">
                    <label>Footer HTML</label>
                    <textarea class="form-control" name="footerHtml" v-model="data.footerHtml"></textarea>
                </div>
                <div class="form-group">
                    <button class="btn btn-primary st-button-submit">Save Changes</button>
                </div>
            </form>
        </div>
    </div>
</template>

<script>
 module.exports = {
     data: function() {
         return {
             data: {
                 footerHtml: '',
                 headHtml: ''
             }
         };
     },
     route: {
         data: function(transition) {
             var self = this;
             this.fetchData(function() {
                 transition.next();
             });
         }
     },
     methods: {
         moment: moment,
         save: function() {
             stallion.request({
                 url: '/st-publisher/config/update-site-settings',
                 method: 'POST',
                 data: this.data,
                 form: this.$el,
                 success: function(o) {
                     stallion.showSuccess("Changes saved");
                 }
             });
         },
         smartFormatDate: function(date) {
             var m = moment(date);
             return m.fromNow();
         },
         fetchData: function(callback) {
             var self = this;
             stallion.request({
                 url: '/st-publisher/config/site-settings',
                 success: function (o) {
                     self.data = o;
                     
                     if (callback) callback();
                 }
             });
         }
     }
 }
</script>
